name: level_maxing
description: "Level Max — AI face scan and looks maxing guide."
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  http: ^0.13.6
  http_parser: ^4.0.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.0
  url_launcher: ^6.3.0
  in_app_purchase: ^3.2.3
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  firebase_crashlytics: ^4.3.10
  in_app_purchase_android: ^0.4.0+10
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_storage: ^12.4.10
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  flutter_windowmanager:
    path: local_plugins/flutter_windowmanager
  screen_capture_event: ^1.2.0
  google_mobile_ads: ^5.1.0
  flutter_timezone: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/